version: 2
updates:
- package-ecosystem: "pip"
  directory: "/ansible/"
  schedule:
    interval: "cron"
    cronjob: "41 7 * * *"
  assignees:
   - "james-otten"
- package-ecosystem: "terraform"
  directory: "/terraform/"
  schedule:
    interval: "cron"
    cronjob: "4 7 * * *"
  assignees:
   - "james-otten"
