proxmox_node             = "jon"
proxmox_storage_location = "local-lvm"
hostname                 = "nycmesh-713-syslog-1"
vm_mgt_ip                = "10.70.90.56"
vm_mgt_default_gateway   = "10.70.90.1"
